version: "3.9"
services:
  go-rest-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - database
    ports:
      - 9090:9090
    volumes:
      - .:/code/

  database:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: admin
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  database-gui-manager:
    image: adminer:fastcgi
    restart: always
    ports:
      - "8282:8282"
    command:
      - 'php'
      - '-S'
      - '[::]:8282'
      - '-t'
      - '/var/www/html'
    entrypoint:
      - 'entrypoint.sh'
      - 'docker-php-entrypoint'
  
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "80:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: doc/openapi.yaml
